cocktails/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes_adviser.urls',
                              namespace='recipes_adviser')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

recipes_adviser/urls.py
from django.conf.urls import url

from . import views


app_name = 'recipes_adviser'

urlpatterns = [
    url(r'^$', views.RecipeSearchView.as_view(), name='index'),
    url(r'^ingredient/(?P<ingredient_id>[0-9]+)/$',
        views.ingredient, name='ingredient_detail'),
    url(r'^recipe/(?P<recipe_id>[0-9]+)/$', views.recipe, name='recipe_detail'),
    url(r'^tool/(?P<tool_id>[0-9]+)/$', views.tool, name='tool_detail'),
    url(r'about/$', views.about, name='about'),
    url(r'about_cocktails/$', views.about_cocktails, name='about_cocktails'),
]

recipes_adviser/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Ingredient(models.Model):
    """ Cocktail's ingredient. """
    name = models.CharField('name', max_length=200, db_index=True)
    liquid = models.BooleanField('is liquid', default=True)
    abv = models.FloatField('alcohol by volume', default=0.0)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=settings.INGREDIENT_IMAGE_PATH,
                              default=settings.DEFAULT_INGREDIENT_IMG,
                              null=True, blank=True)

    # Liquid ingredients are measured in millilitres, non liquid - in grams,
    # something else can measured in units (ice cubes, for example)
    MEASURES = (
        ('g', 'Grams'),
        ('ml', 'Millilitres'),
        ('pcs', 'Pieces')
    )
    measure = models.CharField(max_length=3, choices=MEASURES)

    def __str__(self):
        return self.name


class CocktailComponent(models.Model):
    """ It contains ingredient, quantity and measure of that. """
    ingredient = models.ForeignKey(Ingredient, related_name='components')
    up_quantity = models.FloatField('up quantity of ingredient')
    to_quantity = models.FloatField('to quantity of ingredient',
                                    default=None, null=True, blank=True)

    def __str__(self):
        return '%s (%s - %s)' % (self.ingredient.name,
                                 self.up_quantity,
                                 self.to_quantity)


class RecipeStage(models.Model):
    """
    One stage of cocktail's recipe.
    (Usually a cocktail's recipe has a few stages for making)
    """
    stage_number = models.PositiveSmallIntegerField(default=1)
    content = models.TextField()

    def __str__(self):
        short_content = self.content.split('.')[0][:60]
        return '#%d %s' % (self.stage_number, short_content)

    class Meta:
        ordering = ["stage_number"]


class CocktailTool(models.Model):
    """ Tool for making cocktails. """
    name = models.CharField('name', max_length=200, db_index=True)
    description = models.TextField(blank=True)
    image = models.ImageField(null=True, blank=True,
                              upload_to=settings.TOOL_IMAGE_PATH,
                              default=settings.DEFAULT_TOOL_IMG)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    """ Cocktail's recipe. """
    title = models.CharField('name', max_length=250, db_index=True)
    author = models.ForeignKey(User, related_name='recipes',
                               null=True, blank=True, db_index=True)
    title_image = models.ImageField('title image', null=True, blank=True,
                                    upload_to=settings.RECIPE_IMAGE_PATH,
                                    default=settings.DEFAULT_RECIPE_IMG)
    description = models.TextField(blank=True)

    # Ingredient with quantity
    components = models.ManyToManyField(CocktailComponent,
                                        related_name='recipes')
    stages = models.ManyToManyField(RecipeStage, related_name='recipes')

    tools = models.ManyToManyField(CocktailTool, related_name='recipes')

    COCKTAIL_TYPE = (
        ('st', 'Shot'),
        ('lg', 'Long'),
    )
    type = models.CharField('type of cocktail', max_length=3,
                            choices=COCKTAIL_TYPE)

    def get_min_volume(self):
        """ Returns the sum of min volumes for each liquid components. """
        return sum(item.up_quantity for item in self.components.all()
                   if item.ingredient.liquid)

    def get_max_volume(self):
        """ Returns the sum of max volumes for each liquid components. """
        return sum(item.to_quantity if item.to_quantity else item.up_quantity
                   for item in self.components.all() if item.ingredient.liquid)

    def get_avg_volume(self):
        """ Returns the sum of averages volumes for each liquid components. """
        avg_volume = 0
        for item in self.components.all():
            if item.ingredient.liquid:
                if item.to_quantity:
                    avg_volume += (item.up_quantity + item.to_quantity) / 2.0
                else:
                    avg_volume += item.up_quantity
        return avg_volume

    def get_avg_abv(self):
        volume = self.get_min_volume()
        return sum(item.ingredient.abv * item.up_quantity / volume
                   for item in self.components.all() if item.ingredient.liquid)

    def is_alcoholic(self):
        is_alcoholic = False
        for item in self.components.all():
            if item.ingredient.liquid and item.ingredient.abv > 0.0:
                is_alcoholic = True
                break
        return is_alcoholic

    def is_strong(self):
        """ Returns true if cocktails has average abv more then 17%. """
        strong_abv = 17.0
        return self.get_avg_abv() > strong_abv

    def is_shot(self):
        return self.type == 'st'

    def is_long(self):
        return self.type == 'lg'

    def __str__(self):
        return self.title

recipes_adviser/forms.py
from django import forms


class RecipeSearchForm(forms.Form):
    query = forms.CharField(
        max_length=128,
        required=False,
        widget=forms.TextInput(attrs={
            "class": "cocktails-search-text-field",
            "placeholder": "Поиск"})
    )

    is_long = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={"id": "long-checkbox"})
    )

    is_shot = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={"id": "shot-checkbox"})
    )

    is_strong = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={"id": "strong-checkbox"})
    )

    is_non_alcoholic = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={"id": "non-alcoholic-checkbox"})
    )

recipes_adviser/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.conf import settings
from django.views.generic import View
from django.http import HttpResponse

from .models import Ingredient, Recipe, CocktailTool
from .forms import RecipeSearchForm


class RecipeSearchView(View):
    """ The view for index page with search form for cocktails. """

    RECIPE_PER_PAGE = 30

    def get(self, request):
        form = RecipeSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['query']
            if q:
                recipes = Recipe.objects.filter(title__icontains=q)
            else:
                recipes = Recipe.objects.all()

            if self.is_any_checkbox_pressed(form):
                recipes = self.filter_recipes_by_checkboxes(form, recipes)
        else:
            recipes = Recipe.objects.all()

        if request.is_ajax():
            recipes_num = request.GET.get('recipesNum')
            if not recipes_num:
                return HttpResponse(self.RECIPE_PER_PAGE)
            recipes_num = int(recipes_num)
            recipes = recipes[recipes_num:recipes_num + self.RECIPE_PER_PAGE]
            return render_to_response(
                'recipes_adviser/partials/_recipes_entry.html',
                {"recipes": recipes})

        context = {'recipes_search_form': form,
                   'recipes': recipes[:self.RECIPE_PER_PAGE]}
        return render_to_response('recipes_adviser/index.html', context)

    def is_any_checkbox_pressed(self, form):
        return (form.cleaned_data['is_long']
                or form.cleaned_data['is_shot']
                or form.cleaned_data['is_strong']
                or form.cleaned_data['is_non_alcoholic'])

    def filter_recipes_by_checkboxes(self, form, recipes):
        recipes = self._filter_by_cocktail_type(form, recipes)
        return self._filter_by_alcohol(form, recipes)

    def _filter_by_cocktail_type(self, form, recipes):
        is_long = form.cleaned_data['is_long']
        is_shot = form.cleaned_data['is_shot']
        if not (is_long ^ is_shot):  # xor - return if both checkboxes
            return recipes           # are pressed or both are unpressed
        result = []
        for recipe in recipes:
            if is_long and recipe.is_long():
                result.append(recipe)
            elif is_shot and recipe.is_shot():
                result.append(recipe)
        return result

    def _filter_by_alcohol(self, form, recipes):
        is_strong = form.cleaned_data['is_strong']
        is_non_alc = form.cleaned_data['is_non_alcoholic']
        if not (is_strong ^ is_non_alc):  # xor - return if both checkboxes
            return recipes                # are pressed or both are unpressed
        result = []
        for recipe in recipes:
            if is_strong and recipe.is_strong():
                result.append(recipe)
            elif is_non_alc and not recipe.is_alcoholic():
                result.append(recipe)
        return result


def ingredient(request, ingredient_id):
    ingredient_obj = get_object_or_404(Ingredient, id=ingredient_id)
    if not ingredient_obj.image:
        ingredient_obj.image = {'url': settings.DEFAULT_INGREDIENT_IMG_URL}
    return render_to_response('recipes_adviser/detail_page.html',
                              {'object': ingredient_obj})


def recipe(request, recipe_id):
    cocktail = get_object_or_404(Recipe, id=recipe_id)
    if not cocktail.title_image:
        cocktail.title_image = {'url': settings.DEFAULT_RECIPE_IMG_URL}
    rus_measures = {'ml': 'мл.', 'g': 'гр.', 'pcs': 'шт.'}
    return render_to_response('recipes_adviser/recipe_detail.html',
                              {'recipe': cocktail, 'measures': rus_measures})


def tool(request, tool_id):
    tool_obj = get_object_or_404(CocktailTool, id=tool_id)
    if not tool_obj.image:
        tool_obj.image = {"url": settings.DEFAULT_TOOL_IMG_URL}
    return render_to_response("recipes_adviser/detail_page.html",
                              {"object": tool_obj})


def about(request):
    return render_to_response("recipes_adviser/about.html")


def about_cocktails(request):
    return render_to_response("recipes_adviser/about_cocktails.html")

recipes_adviser/templates/recipes_adviser/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/detail_page_styles.css' %}" />
  <link rel="stylesheet" href="{% static 'css/contacts.css' %}" />
{% endblock head %}



{% block content %}

  <div class="detail-page-container contacts-container">
    <div class="detail-page-block title-container col-xs-12">
      <div class="contacts-title-container">
        <h1 class="site-title">Barkeeper<img src="{% static 'img/cocktail-glass.png' %}"></h1>
      </div><hr>
      <h3>Barkeeper - это ресурс на котором каждый может подобрать себе коктейль по вкусу</h3>
      <p>
        Вы профессиональный бармен и хотите удивить необычным рецептом?<br> Или может быть вы
        хотите стать звездой вечеринки, угостив друзей хорошим коктейлем?<br> А может вы ищите
        освежающий молочный коктейль или смузи для себя и свой семьи?<br> Barkeeper поможет вам
        найти подходящий коткейль и расскажет как его приготовить.
      </p>
      <h4>Barkeeper - это open source проект: </h4><a href="https://github.com/TitovArtem/cocktails">GitHub</a><br>
      <h4>Автор: </h4><span>Титов Артем</span><br><br>МГТУ им. Н.Э. Баумана  2016 г.<br><br>
    </div> <!-- ./detail-page-block -->
  </div>  <!-- ./detail-page-container -->

{% endblock content %}

recipes_adviser/templates/recipes_adviser/about_cocktails.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/detail_page_styles.css' %}" />
{% endblock head %}



{% block content %}

  <div class="detail-page-container">
    <div class="detail-page-block title-container col-xs-12">
      <h1>Виды коктейлей</h1><hr>
      <p>
        Думаю, каждый знает что такое коктейли - напитки, получаемые путем смешивания
        нескольких видов жидкостей. Но какие виды коктейлей вы знаете? Самое очивидное,
        что приходит в голову - это классификация на алкогольные коктейли и безалкогольные.
        Но самом деле не все так просто, если дело касается алкогольных коктейлей.
        Вообще говоря, далеко не всегда так просто определить группу коктейля. Давайте попробуем разобраться.
      </p><hr>
      <h2>Классификация коктейлей по крепкости и объему напитка</h2>
      <p>
        В зависимости от того, какой объём имеет напиток и какова его крепкость,
        различают следующие виды коктейлей:
      </p>
      <ul>
        <li>
          <strong>Hot Drinks</strong> - горячие коктейли. Крепкость данных напитков от 12% до 35%,
          а объем от 60 мл.
        </li>
        <li>
          <strong>Long Drinks</strong> - длинные напитки с крепкостью от 7% до 17% и
          объемом от 160 до 300 мл.
        </li>
        <li>
          <strong>Short Drinks</strong> - крепкие напитки. Объем от 60 до 160 мл,
          крепкость от 17% до 45%.
        </li>
        <li>
          <strong>Shot Drinks</strong> - шоты или напитки, которые выпиваются залпом.
          Обычно имеют объем от 40 до 60 мл и высокую крепкость.
        </li>
      </ul><hr>
      <h2>Классификация напитков по времени употребления</h2>
      <p>
        Некоторые напитки принято пить до еды, другие же после приема пищи. Также есть кокетйли,
        которые одинаково приятно употреблять в любое время, будь то днем или ночью,
        до обеда или после. Рассмотрим каждый тип коктейлей подробнее:
      </p>
      <h3>Аперитивы</h3>
      <p>
        Группа коктейлий, которые принято употреблять до приема пищи. Их основная
        задача - возбудить аппетит. Известными аперитивами являются такие коктейли,
        как <strong>White Lady</strong>, <strong>Dry Martini</strong>, <strong>Kir</strong>.
        На юге европы популярны <strong>Nergoni</strong>, <strong>Americano</strong>, <strong>Picon</strong>.
      </p>
      <h3>Дижестивы</h3>
      <p>
        Группа коктейлей, подаваемая после еды. Часто в них очень большое количество сахара, в том числе и с кофе.
        Яркими представителями этой группы являются коктейли <strong>Черный русский</strong> и <strong>Alexander</strong>.
      </p>
      <h3>Any Time Drinks</h3>
      <p>
        Коктейли данной категории можно смело употреблять в любое время. Это самая популярная
        группа коктейлей, которая пользуется особой популярностью в ночных клубах, барах и на
        вечеринках. Среди популярных представителей этой группы можно отметить такие коктейли,
        как <strong>Маргарита</strong>, <strong>Лонг Айленд</strong> и <strong>Текила санрайз</strong>.
      </p><br>

    </div>
  </div>

{% endblock content %}

recipes_adviser/templates/recipes_adviser/detail_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/detail_page_styles.css' %}" />
{% endblock head %}



{% block content %}

  <!-- container for all items -->
  <div class="detail-page-container">

    <!-- container for the object's name, title image and description -->
    <div class="detail-page-block title-container col-xs-12">
      <div class="col-xs-12 col-md-6 col-lg-6">
        <h1>{{ object.name }}</h1><hr>
        {% if object.description %}
          <p>{{ object.description }}</p>
        {% endif %}
      </div>
      <div class="col-xs-12 col-md-6 col-lg-6">
        <img class="img-responsive" src="{{ IMAGE_URL }}{{ object.image.url }}">
      </div>
    </div> <!-- ./detail-page-block -->
  </div>  <!-- ./detail-page-container -->

  {% endblock content %}

recipes_adviser/templates/recipes_adviser/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <script src="{% static 'js/index.js' %}"></script>
{% endblock head %}


{% block content %}

  {% block logo_area %}

  <!-- logo area -->
  <div class="logo-area">
    <!-- slider -->
    <div id="logo-slider" class="carousel slide" data-ride="carousel" data-interval="false">
      <div class="carousel-inner">
        <!-- slide #1: the form for searching cocktails. -->
        <div class="item active">
          <div class="cocktails-search-form">
            <form action="" method="get">
              <span>
                <i class="loup-search-icon glyphicon glyphicon-search"></i>
                {{ recipes_search_form.query }}
                <input class="cocktails-search-button" type="submit" value="Найти">
              </span>

              <div class="checkbox-container">
                <div class="cocktail-checkbox">
                  {{ recipes_search_form.is_long }}
                  <label for="long-checkbox"><img src="{% static 'img/long.png' %}"></label>
                  <label class="checkbox-labels">лонги</label>
                </div>

                <div class="cocktail-checkbox">
                  {{ recipes_search_form.is_shot }}
                  <label for="shot-checkbox"><img src="{% static 'img/shot.png' %}"></label>
                  <label class="checkbox-labels">шоты</label>
                </div>

                <div class="cocktail-checkbox">
                  {{ recipes_search_form.is_strong }}
                  <label for="strong-checkbox"><img src="{% static 'img/strong.ico' %}"></label>
                  <label class="checkbox-labels">крепкие</label>
                </div>

                <div class="cocktail-checkbox">
                  {{ recipes_search_form.is_non_alcoholic }}
                  <label for="non-alcoholic-checkbox"><img src="{% static 'img/non-alcoholic.ico' %}"></label>
                  <label class="checkbox-labels">без алкоголя</label>
                </div>
              </div>
            </form>
          </div> <!-- /.cocktails-search-form -->
          <!--
          <a class="right carousel-control" href="#logo-slider" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
          -->
        </div> <!-- /slide #1 -->
        <!-- slide #2: the form for searching ingredients. -->
        <!--
        <div class="item">
          <div class="container">
          <h1>Slide 2</h1>
          <a class="left carousel-control" href="#logo-slider" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          </div>
        </div>
        -->
      </div> <!-- /.carousel-inner -->
    </div> <!-- /#logo-slider -->
  </div> <!-- /.logo-area -->
  {% endblock logo_area %}

  {% if not recipes %}
  <div class="errors">
    <h2>Не найдено ни одного рецепта коктейля соответствующего запросу</h2>
    <h5>Попробуйте задать другие критерии поиска и повторить заново</h5>
  </div>
  {% endif %}

  {% if recipes %}
  <div class="recipe-list row">
    {% include 'recipes_adviser/partials/_recipes_entry.html' %}
  </div>
  {% endif %}

  <div class="upload-items-button-container">
    <button id="upload-items-button">
        <span class="glyphicon glyphicon-plus"></span>
        <span class="button-text">Загрузить ещё</span>
    </button>
  </div>

{% endblock content %}

recipes_adviser/templates/recipes_adviser/recipe_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/detail_page_styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/recipe_detail.css' %}" />
{% endblock head %}



{% block content %}

  <!-- container for all items -->
  <div class="detail-page-container">

    <!-- container for the recipe's name, title image and description -->
    <div class="detail-page-block title-container col-xs-12">
      <div class="col-xs-12 col-md-6 col-lg-6">
        <h1>{{ recipe.title }}</h1><hr>
        <!--
        {% if recipe.author %}
          <strong>Автор: </strong> {{ recipe.author }} <br>
        {% endif %}
        -->
        {% if recipe.description %}
          <p>{{ recipe.description }}</p>
        {% endif %}
      </div>
      <div class="col-xs-12 col-md-6 col-lg-6">
        <img class="img-responsive" src="{{ IMAGE_URL }}{{ recipe.title_image.url }}">
      </div>
    </div> <!-- ./detail-page-block -->

    <!-- container for tools, ingredients and stages blocks -->
    <div class="row row-eq-height-lg row-eq-height-md">
      <!-- container for tools and ingredients -->
      <div class="left-shared-block-md col-xs-12 col-lg-6">
        <!-- container for tools -->
        <div class="detail-page-block col-xs-12">
          <h3>Инструменты</h3><hr>
          <ul>
            {% for tool in recipe.tools.all %}
              <li>
                <a href="{% url 'recipes_adviser:tool_detail' tool.id %}"> {{ tool.name }} </a>
              </li>
            {% endfor %}
          </ul><br>
        </div> <!-- end tools container -->

        <!-- container for ingredients -->
        <div class="detail-page-block col-xs-12">
          {% load recipe_extras %}
          <h3>Список ингредиентов</h3><hr>
          <ul>
            {% for item in recipe.components.all %}
              <li>
                <a href="{% url 'recipes_adviser:ingredient_detail' item.ingredient.id %}">
                  {{ item.ingredient.name }}
                </a> -
                <strong>
                  {{ item.up_quantity|floatformat:"0" }}
                  {% if item.to_quantity %}
                    - {{ item.to_quantity|floatformat:"0" }}
                  {% endif %}
                  {{ measures|item:item.ingredient.measure }}
                </strong>
              </li>
            {% endfor %}
          </ul><br>
          </div> <!-- end ingredients container -->
      </div> <!-- end container for tools and ingredients -->

      <!-- container for stages -->
      <div class="detail-page-block col-xs-12 col-lg-6">
        <h3>Этапы приготовления</h3><hr>
        <ol>
          {% for stage in recipe.stages.all %}
            <li><p>{{ stage.content }}</p></li>
          {% endfor %}
        </ol>
      </div> <!-- end stages container -->
    </div> <!-- end container for tools, ingredients and stages -->
  </div>  <!-- ./detail-page-container -->

  {% endblock content %}